### PR TITLE
Fix issue in epubcheck-adapter: MissingFormatArgumentException

### PR DESCRIPTION
**Pull request by josteinaj**
```
java.util.MissingFormatArgumentException: Format specifier '%3$s'
```

This exception appears if you try to validate an unzipped EPUB (i.e. passing in a reference to the OPF instead of an EPUB).

### CODE REVIEW

**Comment by bertfrees** [comment]
Maybe add a test to epub3-validator? It looks like I already had a comment in the existing test related to this: https://github.com/daisy/pipeline-scripts/blob/f54e4a4dbc6c5071c2b8cf12065a4c043d761e8f/epub3-validator/src/test/xprocspec/test.xprocspec#L14.

**Comment by josteinaj** [comment]
I have a test in the nordic migrator: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/pull/353/commits/766356b40513baa0f37e768e24bc647d00da0e72

@bertfrees Could we just change the test you referenced to reference the package document? Would that be sufficient?

**Comment by bertfrees** [comment]
That's probably enough yes.

**Comment by josteinaj** [comment]
I added a regression test here in epubcheck-adapter for this exception.

The epub3-validator script always sets mode to "epub" so I don't think the error will happen there. Although I'm not sure if passing in OPFs will work either when the mode always is "epub"; you would maybe get some other error. I haven't tried that.

**Comment by bertfrees** [comment]
Thanks!

**Comment by bertfrees** [comment]
Merged in 08d01e8

**Pull request merged**
